### ISSUE TITLE
Fixing numerical tolerance

### ISSUE THREAD

**Issue by grjoni** [cmdty/storage#18]
Hi and thx for this model.

I am making a simpel model when I change  max_injection rate from xxx to xxxx i.e 2500 
    
    min_inventory = 0.0,
    max_inventory = 500000.0,
    max_injection_rate = 2500.5,
    max_withdrawal_rate = 3000.9

then I get following error but it says it can be fixed by increasing numerical tolerance but where can I fix it ? 

Inventory constraints cannot be fulfilled. This could potentially be fixed by increasing the numerical tolerance.
   ved Cmdty.Storage.StorageHelper.CalculateBangBangDecisionSet(InjectWithdrawRange injectWithdrawRange, Double currentInventory, Double inventoryLoss, Double nextStepMinInventory, Double nextStepMaxInventory, Double numericalTolerance, Int32 numExtraDecisions)
   ved Cmdty.Storage.IntrinsicStorageValuation`1.OptimalDecisionAndValue(ICmdtyStorage`1 storage, T period, Double inventory, Double nextStepInventorySpaceMin, Double nextStepInventorySpaceMax, Double cmdtyPrice, Func`2 continuationValueByInventory, Double discountFactorFromCmdtySettlement, Func`2 discountFactors, Double numericalTolerance)
   ved Cmdty.Storage.IntrinsicStorageValuation`1.Calculate(T currentPeriod, Double startingInventory, TimeSeries`2 forwardCurve, ICmdtyStorage`1 storage, Func`2 settleDateRule, Func`3 discountFactors, Func`2 gridCalcFactory, IInterpolatorFactory interpolatorFactory, Double numericalTolerance)
   ved Cmdty.Storage.IntrinsicStorageValuation`1.Cmdty.Storage.IIntrinsicCalculate<T>.Calculate()

**Comment by cmdty** [comment]
@grjoni can you please post more details of the Python code you are running so I can see the full details and debug? Might be better to add an attachment.

**Comment by grjoni** [comment]
ok, I was just playing around change some constraints without no problem.

storage = CmdtyStorage(
    freq='D',
    storage_start = '2023-04-01',
    storage_end = '2024-04-01',
    injection_cost = 0.1,
    withdrawal_cost = 0.25,
    
        ratchets= [
                        ('2023-04-01', # For days after 2021-04-01 (inclusive) until 2022-10-01 (exclusive):
                       [
                            (0.0, -150, 250.0),    # At min inventory of zero, max withdrawal of 150, max injection 250
                            (2000.0, -200, 170.0), # At inventory of 2000, max withdrawal of 200, max injection 175
                            (5000.0, -260, 150.0), # At inventory of 5000, max withdrawal of 260, max injection 155
                           # (700.0, -270, 130.0), # At max inventory of 7000, max withdrawal of 275, max injection 132
                        ]),
                  ('2024-04-01', # For days after 2022-10-01 (inclusive):
                       [
                            (0.0, -130.0, 260),    # At min inventory of zero, max withdrawal of 130, max injection 260
                            (2000.0, -190.0, 190), # At inventory of 2000, max withdrawal of 190, max injection 190
                            (5000.0, -230.0, 160), # At inventory of 5000, max withdrawal of 230, max injection 165
                            #(700.0, -24.0, 14), # At max inventory of 7000, max withdrawal of 245, max injection 148
                        ]),

    ],

    ratchet_interp = RatchetInterp.LINEAR
)

----------------------------------------------------------
Then I changed the inventory level by multiply by 10 i.e


storage = CmdtyStorage(
    freq='D',
    storage_start = '2023-04-01',
    storage_end = '2024-04-01',
    injection_cost = 0.1,
    withdrawal_cost = 0.25,
    
        ratchets= [
                        ('2023-04-01', # For days after 2021-04-01 (inclusive) until 2022-10-01 (exclusive):
                       [
                            (0.0, -150, 250.0),    # At min inventory of zero, max withdrawal of 150, max injection 250
                            (20000.0, -200, 170.0), # At inventory of 2000, max withdrawal of 200, max injection 175
                            (50000.0, -260, 150.0), # At inventory of 5000, max withdrawal of 260, max injection 155
                           # (700.0, -270, 130.0), # At max inventory of 7000, max withdrawal of 275, max injection 132
                        ]),
                  ('2024-04-01', # For days after 2022-10-01 (inclusive):
                       [
                            (0.0, -130.0, 260),    # At min inventory of zero, max withdrawal of 130, max injection 260
                            (20000.0, -190.0, 190), # At inventory of 2000, max withdrawal of 190, max injection 190
                            (50000.0, -230.0, 160), # At inventory of 5000, max withdrawal of 230, max injection 165
                            #(700.0, -24.0, 14), # At max inventory of 7000, max withdrawal of 245, max injection 148
                        ]),

    ],
    ratchet_interp = RatchetInterp.LINEAR
)
    

then I get this error 
---------------------------------------------------------------------------
ArgumentException                         Traceback (most recent call last)
<ipython-input-35-34cd0bc7d6e1> in <module>
     14     long_term_vol = long_term_vol,
     15     seasonal_vol = seasonal_vol,
---> 16     basis_funcs = three_factor_basis_functions
     17 )
     18 '{0:,.0f}'.format(three_factor_results.npv)

~\Anaconda3\envs\GasLager\lib\site-packages\cmdty_storage\multi_factor.py in three_factor_seasonal_value(cmdty_storage, val_date, inventory, fwd_curve, interest_rates, settlement_rule, spot_mean_reversion, spot_vol, long_term_vol, seasonal_vol, num_sims, basis_funcs, discount_deltas, seed, fwd_sim_seed, extra_decisions, num_inventory_grid_points, numerical_tolerance, on_progress_update)
    352                                   num_inventory_grid_points, num_sims, numerical_tolerance, on_progress_update,
    353                                   basis_func_transformed, seed, fwd_sim_seed, settlement_rule, time_period_type,
--> 354                                   val_date, discount_deltas, extra_decisions)
    355 
    356 

~\Anaconda3\envs\GasLager\lib\site-packages\cmdty_storage\multi_factor.py in _net_multi_factor_calc(cmdty_storage, fwd_curve, interest_rates, inventory, net_multi_factor_params, num_inventory_grid_points, num_sims, numerical_tolerance, on_progress_update, basis_funcs, seed, fwd_sim_seed, settlement_rule, time_period_type, val_date, discount_deltas, extra_decisions)
    407                                                        inventory, net_forward_curve, net_settlement_rule,
    408                                                        num_inventory_grid_points,
--> 409                                                        numerical_tolerance, time_period_type)
    410     logger.info('Calculation of intrinsic value complete.')
    411 

~\Anaconda3\envs\GasLager\lib\site-packages\cmdty_storage\intrinsic.py in net_intrinsic_calc(cmdty_storage, current_period, interest_rate_time_series, inventory, net_forward_curve, net_settlement_rule, num_inventory_grid_points, numerical_tolerance, time_period_type)
     80     net_cs.IntrinsicStorageValuationExtensions.WithLinearInventorySpaceInterpolation[time_period_type](intrinsic_calc)
     81     net_cs.IIntrinsicAddNumericalTolerance[time_period_type](intrinsic_calc).WithNumericalTolerance(numerical_tolerance)
---> 82     net_val_results = net_cs.IIntrinsicCalculate[time_period_type](intrinsic_calc).Calculate()
     83     data_frame = profile_to_data_frame(cmdty_storage.freq, net_val_results.StorageProfile)
     84     results = IntrinsicValuationResults(net_val_results.NetPresentValue, data_frame)

ArgumentException: Inventory constraints cannot be fulfilled. This could potentially be fixed by increasing the numerical tolerance.
   ved Cmdty.Storage.StorageHelper.CalculateBangBangDecisionSet(InjectWithdrawRange injectWithdrawRange, Double currentInventory, Double inventoryLoss, Double nextStepMinInventory, Double nextStepMaxInventory, Double numericalTolerance, Int32 numExtraDecisions)
   ved Cmdty.Storage.IntrinsicStorageValuation`1.OptimalDecisionAndValue(ICmdtyStorage`1 storage, T period, Double inventory, Double nextStepInventorySpaceMin, Double nextStepInventorySpaceMax, Double cmdtyPrice, Func`2 continuationValueByInventory, Double discountFactorFromCmdtySettlement, Func`2 discountFactors, Double numericalTolerance)
   ved Cmdty.Storage.IntrinsicStorageValuation`1.Calculate(T currentPeriod, Double startingInventory, TimeSeries`2 forwardCurve, ICmdtyStorage`1 storage, Func`2 settleDateRule, Func`3 discountFactors, Func`2 gridCalcFactory, IInterpolatorFactory interpolatorFactory, Double numericalTolerance)
   ved Cmdty.Storage.IntrinsicStorageValuation`1.Cmdty.Storage.IIntrinsicCalculate<T>.Calculate()

I hope it clearify the things ?

Injection max and min are daily and the inventory are noted in MWh  .....

**Comment by cmdty** [comment]
Hi @grjoni I need more information than this to be able to investigate. Can you please also include the code for the call to the valuation function? At the very least I need to see the exact inventory and valuation date used for the valuation, but the more inputs I see, the easier it will be to investigate. Ideally I whole self-contained Python script that I can execute would be good.

**Comment by grjoni** [comment]
#
# https://github.com/cmdty/storage/blob/master/samples/python/multifactor_storage.ipynb
#

Hi thanks for you time, but is this enough information.  I just follow your example 

storage = CmdtyStorage(
    freq='D',
    storage_start = '2023-04-01',
    storage_end = '2024-04-01',
    injection_cost = 0.25,
    withdrawal_cost = 0.25,
    
        ratchets= [
                        ('2023-04-01', # For days after 2021-04-01 (inclusive) until 2022-10-01 (exclusive):
                       [
                            (0.0, -230, 230.0),    # At min inventory of zero, max withdrawal of 230, max injection 230
      
                            (500000.0, -230, 230.0), # At inventory of 5000, max withdrawal of 230, max injection 230
                  
                        ]),
                  ('2024-04-01', # For days after 2022-10-01 (inclusive):
                       [
                            (0.0, -230.0, 230),    # At min inventory of zero, max withdrawal of 230, max injection 230
                      
                            (500000.0, -230.0, 230.0), # At inventory of 5000, max withdrawal of 230, max injection 230
                         
                        ]),

    ],
    ratchet_interp = RatchetInterp.LINEAR
)
    
    
val_date = '2022-10-18'
inventory = 0.0
discount_deltas = True



num_sims = 500
seed = 12
fwd_sim_seed = 25

three_factor_results = three_factor_seasonal_value(
    cmdty_storage = storage,
    val_date = val_date,
    inventory = inventory,
    fwd_curve = fwd_curve,
    interest_rates = ir_curve,
    settlement_rule = settlement_rule,
    discount_deltas=discount_deltas,
    num_sims = num_sims,
    seed = seed,
    fwd_sim_seed = fwd_sim_seed,
    spot_mean_reversion = spot_mean_reversion,
    spot_vol = spot_vol,
    long_term_vol = long_term_vol,
    seasonal_vol = seasonal_vol,
    basis_funcs = three_factor_basis_functions
)
'{0:,.0f}'.format(three_factor_results.npv)


Appreciate your time, regards Grjoni

**Comment by grjoni** [comment]
When I change to settlement to weekly then
I am able to raise the injection volume and the withdrawal ...
 def settlement_rule(delivery_date):
    return delivery_date.asfreq('M').asfreq('W', 'end') + 20

**Comment by rftlab** [comment]
I unfortunately have the same problem. 
Hard to dig into the model itself to understand why it happens...
When I change the first rachet withdrawal value from -16600 to any value below, get the same error.
Increasing numerical_tolerance does not work..


storage_with_ratchets = CmdtyStorage(
    freq='D',
    storage_start = '2023-04-01',
    storage_end = '2024-03-31',
    injection_cost = 0.9,
    withdrawal_cost = 0.3,    ratchets= [
                ('2023-04-01', 
                       [
                            (0.0, -**16600**, 10656),
                            (150000, -26400, 10565), 
                            (999000, -26400, 10565), 
                            (999000, -26400, 10565), 
                        ]),
                 ],
    ratchet_interp = RatchetInterp.STEP
)

**Comment by rftlab** [comment]
Below the full code which ends up the problem with -16400 Withdrawal rate as the first step Rachet, 
Many thanks in advance!!

```
from cmdty_storage import CmdtyStorage, RatchetInterp,three_factor_seasonal_value
import pandas as pd


storage_with_ratchets = CmdtyStorage(
    freq='D',
    storage_start = '2023-04-01',
    storage_end = '2024-03-31',
    injection_cost = 0.9,
    withdrawal_cost = 0.3,
    ratchets= [
                ('2023-04-01', # For days after 2021-04-01 (inclusive) until 2022-10-01 (exclusive):
                       [
                            (0.0, -16400, 10656),
                            (150000, -26400, 10565), 
                            (999000, -26400, 10565), 
                            (999000, -26400, 10565), 
                        ]),

                 ],
    ratchet_interp = RatchetInterp.STEP
)
    
# Creating the Inputs
monthly_index = pd.period_range(start='2022-11-01', periods=25, freq='M')
monthly_fwd_prices = [123, 122, 123, 122.6, 122, 123, 122, 125, 126, 124, 
                      121, 120, 119, 120, 118, 118, 118, 117,116.2 ,116.5, 
                      116, 116.2, 115.2, 115, 115]
fwd_curve = pd.Series(data=monthly_fwd_prices, index=monthly_index).resample('D').fillna('pad')

rates = [0.005, 0.006, 0.0072, 0.0087, 0.0101, 0.0115, 0.0126]
rates_pillars = pd.PeriodIndex(freq='D', data=['2023-04-01', '2023-06-01', '2023-08-01', '2023-12-01', '2024-04-01', 
                                              '2024-12-01', '2025-01-01'])
ir_curve = pd.Series(data=rates, index=rates_pillars).resample('D').asfreq('D').interpolate(method='linear')

def settlement_rule(delivery_date):
    return delivery_date.asfreq('M').asfreq('D', 'end')

# Call the three-factor seasonal model
three_factor_results = three_factor_seasonal_value(
    cmdty_storage = storage_with_ratchets,
    val_date = '2023-04-01',
    inventory = 0.0,
    fwd_curve = fwd_curve,
    interest_rates = ir_curve,
    settlement_rule = settlement_rule,
    numerical_tolerance=1,
    num_sims = 2000,
    seed = 12,
    spot_mean_reversion = 43.0,
    spot_vol = 0.13,
    long_term_vol =  0.40,
    seasonal_vol = 0.18,
    basis_funcs = '1 + x_st + x_sw + x_lt + s + x_st**2 + x_sw**2 + x_lt**2 + s**2 + s * x_st',
    discount_deltas = True
)

# Inspect the NPV results
print('Full NPV:\t{0:,.0f}'.format(three_factor_results.npv))
print('Intrinsic NPV: \t{0:,.0f}'.format(three_factor_results.intrinsic_npv))
print('Extrinsic NPV: \t{0:,.0f}'.format(three_factor_results.extrinsic_npv))    
```

**Comment by cmdty** [comment]
@rftlab this is a recurring problem with step ratchets, and can usually be fixed by not constraining the storage to be empty at the end. This is done by defining the storage NPV at the end by assigning to the terminal_storage_npv argument to the CmdtyStorage constructor. For example if you want to define any inventory as worthless at the end you can use something like:
 
    terminal_storage_npv = lambda spot_price, inventory: 0.0

**Comment by rftlab** [comment]
@cmdty thanks.  It somehow happens also with Linear Rachets too.
Tried to assign 0 to terminal_storage_npv  in the CmdtyStorage constructor as you suggested above. Still get the same problem. 
Anyhow, thanks for the help !

**Comment by cmdty** [comment]
@rftlab I’ll take a proper look at this tonight.

**Comment by cmdty** [comment]
@rftlab I just ran the above code with step ratchets and terminal_storage_npv set as described in my last comment and it runs with no exception. I'm using version 1.0.0 of the PyPI package.

Next I tried Linear ratches, and terminal_storage_npv not set and got the exception. However, I got rid of the exception by removing the last 2 ratchets as they are superfluous due to having the same injection and withdrawal rates. Here is the CmdtyStorage creation code.

storage_with_ratchets = CmdtyStorage(
    freq='D',
    storage_start = '2023-04-01',
    storage_end = '2024-03-31',
    injection_cost = 0.9,
    withdrawal_cost = 0.3,
    ratchets= [
                ('2023-04-01', # For days after 2021-04-01 (inclusive) until 2022-10-01 (exclusive):
                       [
                            (0.0, -16400, 10656),
                            (150000, -26400, 10565), 
                        ]),

                 ],
    ratchet_interp = RatchetInterp.LINEAR,
)
